//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stage
    {
        public string id { get; set; }
        public string name { get; set; }
        public string studentId { get; set; }
    
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
    }
}
