//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WbAppMVC.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        public student()
        {
            this.parents = new HashSet<parent>();
            this.subjects = new HashSet<subject>();
            this.stages = new HashSet<stage>();
        }
        [Required]
        public string firstname { get; set; }

        [Required]
        public string secondname { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }

        [Required]
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> wallet { get; set; }

        [Required]
        public string thirdname { get; set; }
        public string Id { get; set; }

        [JsonIgnore]
        public virtual ICollection<parent> parents { get; set; }

        [JsonIgnore]
        public virtual stage stage { get; set; }

        [JsonIgnore]
        public virtual ICollection<subject> subjects { get; set; }

        [JsonIgnore]
        public virtual ICollection<stage> stages { get; set; }
    }
}
